'use client'

import { useEffect, useState } from 'react'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Badge } from '@/components/ui/badge'
import { apiClient } from '@/services/api'
import { Loader2, Sparkles } from 'lucide-react'
import { toast } from 'sonner'

export default function RecommendationsPage() {
  const [recommendations, setRecommendations] = useState<any[]>([])
  const [loading, setLoading] = useState(true)
  const [deployingId, setDeployingId] = useState<string | null>(null)
  const [deployedIds, setDeployedIds] = useState<string[]>([])

  useEffect(() => {
    async function fetchRecommendations() {
      try {
        const response = await apiClient.get('/api/recommendations')
        setRecommendations(response.data || response)
      } catch (error) {
        console.error('Failed to load live recommendations:', error)
        toast.error('Failed to load AI recommendations.')
      } finally {
        setLoading(false)
      }
    }
    fetchRecommendations()
  }, [])

  const handleDeployOffer = async (customerId: string, strategy: string) => {
    setDeployingId(customerId)
    try {
      await apiClient.post('/api/recommendations/deploy', { customerId, strategy })
      setDeployedIds((prev) => [...prev, customerId])
      toast.success(`Retention offer successfully deployed for account ${customerId}!`)
    } catch (error: any) {
      toast.error(error.response?.data?.detail || 'Failed to deploy retention offer.')
    } finally {
      setDeployingId(null)
    }
  }

  if (loading) {
    return (
      <div className="flex h-[80vh] items-center justify-center">
        <Loader2 className="h-8 w-8 animate-spin text-primary" />
      </div>
    )
  }

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-3xl font-bold text-foreground">AI Retention Recommendations</h1>
        <p className="text-muted-foreground mt-2">
          Live action plans generated by your Python rules engine for at-risk customers in your dataset.
        </p>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
        {recommendations.map((rec, index) => {
          const rawRisk = rec.customerRisk || rec.risk || 0.78
          const riskPercentage = rawRisk <= 1 ? Math.round(rawRisk * 100) : Math.round(rawRisk)
          const customerId = rec.customerId || rec.id
          const strategyText = rec.action || rec.strategy || 'Deploy custom loyalty discount.'
          const isDeployed = deployedIds.includes(customerId)
          const isDeploying = deployingId === customerId

          return (
            <Card key={index} className="border-border bg-card flex flex-col justify-between shadow-md">
              <CardHeader>
                <div className="flex items-center justify-between">
                  <CardTitle className="text-foreground text-lg">{rec.customerName || rec.name}</CardTitle>
                  <Badge className="bg-red-500/25 text-red-300 border-red-500/40 border font-semibold">
                    Risk: {riskPercentage}%
                  </Badge>
                </div>
                <p className="text-xs text-muted-foreground mt-1">ID: {customerId}</p>
              </CardHeader>
              <CardContent className="space-y-4">
                <div className="bg-muted/30 p-3 rounded-md border border-border">
                  <p className="text-xs font-semibold text-primary mb-1 flex items-center gap-1">
                    <Sparkles className="h-3.5 w-3.5" /> Action Plan
                  </p>
                  <p className="text-sm text-foreground">{strategyText}</p>
                </div>

                <div>
                  <p className="text-xs font-medium text-muted-foreground mb-1">Risk Factors:</p>
                  <ul className="text-xs text-muted-foreground space-y-1">
                    {rec.causes?.map((cause: string, i: number) => (
                      <li key={i} className="flex items-center gap-1.5">
                        <span className="h-1.5 w-1.5 rounded-full bg-primary" />
                        {cause}
                      </li>
                    ))}
                  </ul>
                </div>

                <Button
                  onClick={() => handleDeployOffer(customerId, strategyText)}
                  disabled={isDeploying || isDeployed}
                  className={`w-full mt-2 transition-all ${
                    isDeployed
                      ? 'bg-green-600/20 text-green-300 border border-green-500/30 hover:bg-green-600/30'
                      : 'bg-primary text-primary-foreground hover:bg-primary/95'
                  }`}
                >
                  {isDeploying ? (
                    <Loader2 className="h-4 w-4 animate-spin" />
                  ) : isDeployed ? (
                    'Offer Deployed ✓'
                  ) : (
                    'Deploy Retention Offer'
                  )}
                </Button>
              </CardContent>
            </Card>
          )
        })}
      </div>
    </div>
  )
}