'use client'

import { useEffect, useState } from 'react'
import { AlertCircle, BrainCircuit, Loader2 } from 'lucide-react'
import { adaptiveApi, type Project } from '@/services/adaptive'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'

export default function ExplainabilityPage() {
  const [projects, setProjects] = useState<Project[]>([]); const [projectId, setProjectId] = useState(''); const [datasetId, setDatasetId] = useState(''); const [customerKey, setCustomerKey] = useState(''); const [global, setGlobal] = useState<Array<{ feature: string; meanAbsoluteShap: number }>>([]); const [local, setLocal] = useState<Array<{ feature: string; shapValue: number }>>([]); const [loading, setLoading] = useState(false); const [error, setError] = useState('')
  useEffect(() => { adaptiveApi.listProjects().then((items) => { setProjects(items); if (items[0]) setProjectId(items[0].id) }).catch((reason) => setError(String(reason))) }, [])
  const globalExplain = async () => { if (!projectId || !datasetId) return; setLoading(true); setError(''); try { setGlobal((await adaptiveApi.explainGlobal(projectId, datasetId)).features) } catch (reason) { setError(reason instanceof Error ? reason.message : 'Global SHAP generation failed.') } finally { setLoading(false) } }
  const localExplain = async () => { if (!projectId || !datasetId || !customerKey) return; setLoading(true); setError(''); try { setLocal((await adaptiveApi.explainLocal(projectId, datasetId, customerKey)).contributions) } catch (reason) { setError(reason instanceof Error ? reason.message : 'Local SHAP generation failed.') } finally { setLoading(false) } }
  const max = Math.max(...global.map((item) => item.meanAbsoluteShap), 1)
  return <div className="space-y-6"><div><p className="text-xs font-semibold uppercase tracking-[.18em] text-pink-500">Saved model evidence</p><h1 className="mt-2 text-3xl font-bold">Explainability</h1><p className="mt-2 text-sm text-slate-500">SHAP results are computed only from a trained saved model and its canonical preprocessing contract, then persisted with the selected dataset and model.</p></div>{error && <div className="flex gap-2 rounded-lg bg-red-50 p-3 text-sm text-red-700"><AlertCircle className="h-5 w-5"/>{error}</div>}<Card><CardContent className="grid gap-3 p-5 md:grid-cols-3"><select value={projectId} onChange={(event) => setProjectId(event.target.value)} className="rounded-lg border p-2 text-sm"><option value="">Select project</option>{projects.map((project) => <option key={project.id} value={project.id}>{project.name}</option>)}</select><input value={datasetId} onChange={(event) => setDatasetId(event.target.value)} placeholder="Dataset ID" className="rounded-lg border p-2 text-sm"/><input value={customerKey} onChange={(event) => setCustomerKey(event.target.value)} placeholder="Optional customer identifier" className="rounded-lg border p-2 text-sm"/></CardContent><CardContent className="flex flex-wrap gap-3 pt-0"><Button disabled={loading || !datasetId} onClick={globalExplain}>{loading ? <Loader2 className="mr-2 h-4 w-4 animate-spin"/> : <BrainCircuit className="mr-2 h-4 w-4"/>}Global SHAP</Button><Button variant="outline" disabled={loading || !datasetId || !customerKey} onClick={localExplain}>Local SHAP</Button></CardContent></Card><div className="grid gap-5 lg:grid-cols-2"><Card><CardHeader><CardTitle>Global importance</CardTitle></CardHeader><CardContent className="space-y-4">{global.length ? global.slice(0, 12).map((item) => <div key={item.feature}><div className="flex justify-between gap-4 text-sm"><span className="truncate">{item.feature}</span><span className="font-mono text-slate-500">{item.meanAbsoluteShap.toFixed(6)}</span></div><div className="mt-1 h-2 rounded-full bg-slate-100"><div className="h-2 rounded-full bg-pink-500" style={{ width: `${(item.meanAbsoluteShap / max) * 100}%` }}/></div></div>) : <p className="text-sm text-slate-500">Run global SHAP after selecting a trained binary-classification dataset.</p>}</CardContent></Card><Card><CardHeader><CardTitle>Customer drivers</CardTitle></CardHeader><CardContent className="space-y-2">{local.length ? local.slice(0, 12).map((item) => <div key={item.feature} className="flex justify-between rounded-lg bg-slate-50 p-2 text-sm"><span>{item.feature}</span><span className={item.shapValue >= 0 ? 'text-red-600' : 'text-green-600'}>{item.shapValue.toFixed(6)}</span></div>) : <p className="text-sm text-slate-500">Enter a real identifier from the selected dataset and run local SHAP.</p>}</CardContent></Card></div></div>
}
