'use client'

import { useEffect, useState } from 'react'
import { AlertCircle, Loader2, Sparkles } from 'lucide-react'
import { adaptiveApi, type Project } from '@/services/adaptive'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'

export default function RecommendationsPage() {
  const [projects, setProjects] = useState<Project[]>([]); const [projectId, setProjectId] = useState(''); const [datasetId, setDatasetId] = useState(''); const [customerKey, setCustomerKey] = useState(''); const [result, setResult] = useState<any>(null); const [history, setHistory] = useState<any[]>([]); const [loading, setLoading] = useState(false); const [error, setError] = useState('')
  useEffect(() => { adaptiveApi.listProjects().then((items) => { setProjects(items); if (items[0]) setProjectId(items[0].id) }).catch((reason) => setError(String(reason))) }, [])
  const generate = async () => { if (!projectId || !datasetId || !customerKey) return; setLoading(true); setError(''); try { const value = await adaptiveApi.recommend(projectId, datasetId, customerKey); setResult(value); setHistory(await adaptiveApi.listRecommendations(projectId, datasetId)) } catch (reason) { setError(reason instanceof Error ? reason.message : 'Recommendation generation failed.') } finally { setLoading(false) } }
  return <div className="space-y-6"><div><p className="text-xs font-semibold uppercase tracking-[.18em] text-pink-500">Model-informed action layer</p><h1 className="mt-2 text-3xl font-bold">Recommendations</h1><p className="mt-2 text-sm text-slate-500">Recommendations cite a real prediction, the stored production threshold, SHAP drivers, and semantic roles inferred from the uploaded schema. They do not invent expected retention rates.</p></div>{error && <div className="flex gap-2 rounded-lg bg-red-50 p-3 text-sm text-red-700"><AlertCircle className="h-5 w-5"/>{error}</div>}<Card><CardContent className="grid gap-3 p-5 md:grid-cols-3"><select value={projectId} onChange={(event) => setProjectId(event.target.value)} className="rounded-lg border p-2 text-sm"><option value="">Select project</option>{projects.map((project) => <option key={project.id} value={project.id}>{project.name}</option>)}</select><input value={datasetId} onChange={(event) => setDatasetId(event.target.value)} placeholder="Dataset ID" className="rounded-lg border p-2 text-sm"/><input value={customerKey} onChange={(event) => setCustomerKey(event.target.value)} placeholder="Customer identifier" className="rounded-lg border p-2 text-sm"/></CardContent><CardContent className="pt-0"><Button disabled={loading || !projectId || !datasetId || !customerKey} onClick={generate}>{loading ? <Loader2 className="mr-2 h-4 w-4 animate-spin"/> : <Sparkles className="mr-2 h-4 w-4"/>}Generate evidence-backed action</Button></CardContent></Card>{result && <Card className="border-pink-200"><CardHeader><CardTitle>{result.recommendation.recommendationText}</CardTitle></CardHeader><CardContent className="space-y-3"><p className="text-sm text-slate-600">{result.recommendation.reason}</p><div className="grid gap-3 sm:grid-cols-3"><Fact label="Probability" value={result.prediction.probability.toFixed(6)}/><Fact label="Threshold" value={result.prediction.threshold.toFixed(4)}/><Fact label="Rule" value={result.recommendation.ruleKey}/></div></CardContent></Card>}{history.length > 0 && <Card><CardHeader><CardTitle>Persisted recommendation records</CardTitle></CardHeader><CardContent className="space-y-2">{history.map((item) => <div key={item.id} className="rounded-lg border p-3 text-sm"><b>{item.customerKey}</b> · {item.recommendation.recommendationText}<p className="mt-1 text-xs text-slate-500">{item.generatedAt}</p></div>)}</CardContent></Card>}</div>
}

function Fact({ label, value }: { label: string; value: string }) { return <div className="rounded-lg bg-slate-50 p-3"><p className="text-xs uppercase text-slate-500">{label}</p><p className="mt-1 break-words font-medium">{value}</p></div> }
